### PR TITLE
Hi i fixed some stuff for the wrapper.

### PR DESCRIPTION
**Pull request by stonerl**
I fixed the offline notifications, added multiuser support (maybe this needs some testing) and fixed startup notification (they showed up even when they were turned off)

### CODE REVIEW

**Comment by grissir** [comment]
thanks for the work I'll test your changes soon
Am 11.08.2012 22:32, schrieb Toni F:

**Comment by grissir** [comment]
k I tested some things but now something crashed and neither your nor the main branch are currently working, sorry have a lot of stuff to do currently so it can take some time

**Comment by stonerl** [comment]
@sagetarian i will have a look. The reason i changed it was that Skype just picks some random chatmessage as topic for the friendly which is, IMHO, very confusing.

@grissir thank you for testing, what exactly crashed? Currently everything is working fine for me...

**Comment by grissir** [comment]
It seems a problem of my system, I can't even start the stable 
skype-wrapper.
Ok strange now it works, I'll try to reproduce it

**Comment by grissir** [comment]
k now everything works as expected
I merge it

**Comment by stonerl** [comment]
great thanks allot

**Comment by grissir** [comment]
I have a bad feeling, I forgot to test conversations when the conversation window is closed -.-

**Comment by stonerl** [comment]
I will test this later as when i'm back home. As far as I remember it worked for me... I will have a look

**Pull request merged**
